# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  frontend_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 13
        
    - name: Install dependencies
      run: npm install
      working-directory: frontend
      
    - name: Style checks
      run: npm run stylelint
      working-directory: frontend

    - name: Code linting
      run: npm run eslint
      working-directory: frontend

    - name: Run frontend tests
      run: npm run test -- --watchAll=false --coverage
      working-directory: frontend
  
  deploy:
    needs: [frontend_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
          version: 13
      
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      
      - name: Build project
        run: npm run build
        working-directory: frontend
        
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.0.1
        with:
          # Auth token to use with netlify
          NETLIFY_AUTH_TOKEN: ${{secrets.CODECOV_TOKEN}}
          # Your Netlify site id
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          # A deploy message
          NETLIFY_DEPLOY_MESSAGE: Deploy enginally
          # Directory where built files are stored
          build_directory: build
          # Directory where built files are stored
          functions_directory: build
